apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: default  
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"superset","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8088}],"selector":{"app":"superset"},"type":"LoadBalancer"}}
    service.beta.kubernetes.io/aws-load-balancer-subnet: "subnet-0aec9ef6bbbfe752e,subnet-0f0e4632b38a4494a"
spec:
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 8088  # Port on which Superset is running
  type: LoadBalancer

